### ISSUE TITLE
Cant save items and categories

### ISSUE THREAD

**Issue by joomlaplates** [joomlaworks/k2-v3-dev-build#129] opened 2014-12-12 22:23 UTC
Hi there, I cant save new items and categories if the "rokpad editor is enabled.
Joomla 3.3.6, Original Protostar Template, K2 v3-dev.
And the "column" settings are not working. I have set 4 article with 3 column and it shows only 1 column!

![column](https://cloud.githubusercontent.com/assets/1214035/5420587/756095fc-8257-11e4-851b-1260c8e6eb9a.jpg)

**Comment by paulvanharen** [comment] 2016-01-26 18:09
@kavadas 
I propose to close this issue. The front-end has been updated in the september 2015 update; the other part is a duplicate of #52.

**Closed** 2016-01-27 08:48 UTC
Labels: duplicate
