### ISSUE TITLE
Disable "User Extended Fields for K2 v3.0" to load Homepage

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomlaworks/k2-v3-dev-build#149] opened 2014-12-16 18:15 UTC
Cant load Homepage until disabling UEFv3.0.

**Comment by paulvanharen** [comment] 2016-01-25 18:08
@kavadas 
I cannot reproduce this issue. Therefore I propose closing this issue.

**Closed** 2016-01-26 13:18 UTC
