### ISSUE TITLE
K2_CATEGORY_VIEW_OPTIONS

### ISSUE THREAD

**Issue by JHEXP** [joomlaworks/k2-v3-dev-build#2] opened 2014-07-22 07:36 UTC
In 
Sub-category handling

Columns number seems not work! 
Displaying the sub-category only in 1 column

**Comment by JHEXP** [comment] 2015-01-06 10:09
Hi Paul, excuse me for the delay (and for my bad english).

It happens in new install of k2 in a fresh joomla installation..

( the site is http://www.enos.joomlafree.it a free hosting service)

I have created a  Notiziario category and 2 subcategory (anno2013 and anno 2014 that are children of the "root" category Notiziario).

I have set the display option of category Notiziario to show the subcategory in 2 column but in front end the subcategory are shown in 1 column.

(and Also i have seen that the option of "image size" in K2_CATEGORY_LAYOUT_OPTIONS is not actived)

**Comment by paulvanharen** [comment] 2015-01-06 11:08
Dear JHEXP,

Thank you for your reply. The example confirms the root cause of the bug: after a fresh install there are no default settings for K2 and as a consequence, the k2.css is not loaded. 

A quick work around is to go to "global configuration", and simply open-and-save the k2 settings. This will set the missing defaults. 

I created a fixed to solve the problem during installation. That fix is waiting for integration with the main development tree.

Thanks and regards, Paul

**Comment by JHEXP** [comment] 2015-01-06 11:44
Oh!
I have done open-and-save k2 settings and now k2 works fine!

Thank you Paul

**Comment by paulvanharen** [comment] 2016-01-25 17:56
@kavadas 
I tried to reproduce this issue but could not. I expect that this issue is solved with the code updates in September 2015. Therefore, I propose to close this issue.

**Closed** 2016-01-26 13:16 UTC
Labels: bug
