### ISSUE TITLE
Category-Items shown in 1 Column

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomlaworks/k2-v3-dev-build#151] opened 2014-12-17 11:19 UTC
Items in Categorys are shown in 1 Column, if set to 2 ore other Value. Tested with System-Template same Result.

**Comment by paulvanharen** [comment] 2016-01-25 18:09
@kavadas 
I guess this is a duplicate of #2. Therefore I propose closing this issue.

**Closed** 2016-01-26 13:19 UTC
