### ISSUE TITLE
mod_k2_content introText word limit not working

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/k2-v3-dev-build#241] opened 2015-09-18 03:07 UTC
Setting a word limit in mod_k2_content doesn't work, completely ignoring if this is set in the module params.

**Comment by kavadas** [comment] 2015-09-18 08:38
I cannot verify the issue. The option works fine for me.

**Comment by paulvanharen** [comment] 2016-01-26 18:18
@kavadas 
I cannot reproduce this issue as well. Therefore I propose to close this issue.

**Closed** 2016-01-26 18:31 UTC
